server:
  port: 3000

spring:
  application:
    name: project-2

search:
  index:
    path: target/index
    ram_buffer_size_mb: 2048.0
  sources:
    path: target/sources/html
  synonyms:
    path: src/main/resources/synonyms.txt