from dataclasses import dataclass

@dataclass
class ExtractionExample:
    table: str
    caption: str
    references: list[str]
    result: str

    def __str__(self):
        return f"""
        [Table]: 
        {self.table}
        [Caption]: 
        {self.caption}
        [References]: 
        {self.references}
        [Response]: 
        {self.result}
        """

example1 = ExtractionExample(
    table="""
    ----------  -------------  -------------  -------------  -------------  -------------  -------------
                Lively         Lively         Harsh          Harsh          Wellcoming     Wellcoming
    Model       SI-MOS         N-MOS          SI-MOS         N-MOS          SI-MOS         N-MOS
    GT          4.49  ±  0.14  4.28  ±  0.38  4.52  ±  0.14  4.85  ±  0.21  4.01  ±  0.26  4.28  ±  0.29
    Synth none  2.67  ±  0.26  1.74  ±  0.24  2.71  ±  0.14  2.20  ±  0.22  2.63  ±  0.17  2.33  ±  0.27
    Synth TTS   2.65  ±  0.15  2.55  ±  0.16  2.17  ±  0.15  2.11  ±  0.19  2.99  ±  0.14  2.55  ±  0.27
    Synth both  2.24  ±  0.14  2.90  ±  0.31  2.25  ±  0.15  2.28  ±  0.20  3.06  ±  0.17  3.44  ±  0.28
    VC          3.04  ±  0.16  3.66  ±  0.26  1.93  ±  0.29  3.66  ±  0.38  3.61  ±  0.19  3.95  ±  0.54
    ----------  -------------  -------------  -------------  -------------  -------------  -------------
    """,
    caption="Table 3: Style Intensity (SI-MOS) and Naturalness (N-MOS) Mean Opinion Scores with 95% confidence intervals.",
    references=[
        """
        The results indicate that synthetic data generated by voice conversion (VC) exhibit higher naturalness than those from cross-speaker style transfer experiments.
        Consequently, both the Synth TTS and Synth both experiments, which incorporate synthetic data during training, show increased naturalness compared to Synth None, with Synth both demonstrating the highest improvement.
        However, we note that for style intensity, the Synth none configuration performed better in two out of three expressive styles in the dataset, despite having lower naturalness in each case (Table 3).
        """
    ],
    result="""
    { "Model": "GT", "Speaker-Style": "Lively", "SI-MOS": "4.49 ± 0.14", "N-MOS": "4.28 ± 0.38" },
    { "Model": "GT", "Speaker-Style": "Harsh", "SI-MOS": "4.52 ± 0.14", "N-MOS": "4.85 ± 0.21" },
    { "Model": "GT", "Speaker-Style": "Wellcoming", "SI-MOS": "4.01 ± 0.26", "N-MOS": "4.28 ± 0.29" },
    { "Model": "Synth none", "Speaker-Style": "Lively", "SI-MOS": "2.67 ± 0.26", "N-MOS": "1.74 ± 0.24" },
    { "Model": "Synth none", "Speaker-Style": "Harsh", "SI-MOS": "2.71 ± 0.14", "N-MOS": "2.20 ± 0.22" },
    { "Model": "Synth none", "Speaker-Style": "Wellcoming", "SI-MOS": "2.63 ± 0.17", "N-MOS": "2.33 ± 0.27" },
    { "Model": "Synth TTS", "Speaker-Style": "Lively", "SI-MOS": "2.65 ± 0.15", "N-MOS": "2.55 ± 0.16" },
    { "Model": "Synth TTS", "Speaker-Style": "Harsh", "SI-MOS": "2.17 ± 0.15", "N-MOS": "2.11 ± 0.19" },
    { "Model": "Synth TTS", "Speaker-Style": "Wellcoming", "SI-MOS": "2.99 ± 0.14", "N-MOS": "2.55 ± 0.27" },
    { "Model": "Synth both", "Speaker-Style": "Lively", "SI-MOS": "2.24 ± 0.14", "N-MOS": "2.90 ± 0.31" },
    { "Model": "Synth both", "Speaker-Style": "Harsh", "SI-MOS": "2.25 ± 0.15", "N-MOS": "2.28 ± 0.20" },
    { "Model": "Synth both", "Speaker-Style": "Wellcoming", "SI-MOS": "3.06 ± 0.17", "N-MOS": "3.44 ± 0.28" },
    { "Model": "Voice Conversion (VC)", "Speaker-Style": "Lively", "SI-MOS": "3.04 ± 0.16", "N-MOS": "3.66 ± 0.26" },
    { "Model": "Voice Conversion (VC)", "Speaker-Style": "Harsh", "SI-MOS": "1.93 ± 0.29", "N-MOS": "3.66 ± 0.38" },
    { "Model": "Voice Conversion (VC)", "Speaker-Style": "Wellcoming", "SI-MOS": "3.61 ± 0.19", "N-MOS": "3.95 ± 0.54" }
    """
)
