server:
  port: 3000

spring:
  application:
    name: project-2

search:
  index:
    paper:
      path: target/index/paper
      recreate: false
    table:
      path: target/index/table
      recreate: true
    ram_buffer_size_mb: 2048.0
    use_debug_codec: false
  sources:
    paper:
      path: target/sources/html
    table:
      path: target/sources/all_tables
  synonyms:
    path: synonyms.txt